### ISSUE TITLE
Library version r7 not working with Arduino 1.0.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jwhiddon/arduino-at24c1024#1]
```
What steps will reproduce the problem?
1. use library version r7 with Arduino IDE 1.0.1
2. errors when try to compile 


Please provide any additional information below.

I have fixed library for Arduino IDE 1.0.1
See attached file.

Tested with Arduino UNO and Arduino IDE 1.0.1 on Windows 7 x64.

```

Original issue reported on code.google.com by `martinko...@gmail.com` on 14 Aug 2012 at 11:34

Attachments:
- [E24C1024_1.0.1.zip](https://storage.googleapis.com/google-code-attachments/arduino-at24c1024/issue-1/comment-0/E24C1024_1.0.1.zip)

**Comment by GoogleCodeExporter** [comment]
```
我也遇到這個問題
I have encountered this problem

C:\Program Files (x86)\Arduino\libraries\E24C1024\E24C1024.cpp: In static 
member function 'static void E24C1024::write(long unsigned int, uint8_t)':
C:\Program Files (x86)\Arduino\libraries\E24C1024\E24C1024.cpp:56: error: 
'class TwoWire' has no member named 'send'
C:\Program Files (x86)\Arduino\libraries\E24C1024\E24C1024.cpp:57: error: 
'class TwoWire' has no member named 'send'
C:\Program Files (x86)\Arduino\libraries\E24C1024\E24C1024.cpp:58: error: 
'class TwoWire' has no member named 'send'
C:\Program Files (x86)\Arduino\libraries\E24C1024\E24C1024.cpp:60: error: 
'delay' was not declared in this scope
C:\Program Files (x86)\Arduino\libraries\E24C1024\E24C1024.cpp: In static 
member function 'static uint8_t E24C1024::read(long unsigned int)':
C:\Program Files (x86)\Arduino\libraries\E24C1024\E24C1024.cpp:67: error: 
'class TwoWire' has no member named 'send'
C:\Program Files (x86)\Arduino\libraries\E24C1024\E24C1024.cpp:68: error: 
'class TwoWire' has no member named 'send'
C:\Program Files (x86)\Arduino\libraries\E24C1024\E24C1024.cpp:71: error: 
'class TwoWire' has no member named 'receive'

```

Original comment by `nm125...@gmail.com` on 4 Feb 2015 at 5:26

**Comment by jwhiddon** [comment]
Fixed
